### ISSUE TITLE
Changing data always uses addData

### ISSUE THREAD

**Issue by cloke** [MLHale/ember-heatmap#2]
I am working on a tool that lets users look at different datasets using the heat map. The dataChanged method always uses the addData call but in my case I want it to set a new data and not add to existing data. I can make this a configurable option in a PR, but wanted any insight into this choice before doing so.

My other option is to destroy the component on every new dataset, but that seems like a more intensive task.

@MLHale

**Comment by MLHale** [comment]
I use addData currently, because it is way more efficient than entirely swapping out the dataset every time a new point is added. In my case, I wrote the component for heatmaps that were being constantly updated (at a rate of 100hz), so it was really inefficient to entirely swap the dataset out each time. In your case, that isn't a problem. 

It sounds like you should just clear the existing heatmap stored by heatmap.js and reinitialize it.

One way to do this (without respecting bindings) would be using the `setData()` method provide by the heatmap.js api.
see: https://www.patrick-wied.at/static/heatmapjs/docs.html#heatmap-setData
You will see that the setData function clears the existing data in the array before setting it to whatever new data you pass in. I just wrap this function, in the setupHeatmap function in the ember component. 

### Solution that disrespects ember bindings
a `swapDataset` method for this ember-heatmap plugin would need to invoke `setData()`, e.g.
```
swapDataset(dataset, max, min){
      this.set('hasRendered', false);//turn off observer
      this.get('map').setData({ //reinitialize data map for rerender
           max: max,
           min: min,
           data: dataset
      });
     this.set('hasRendered', true); //turn on observer again in case you add new points
```

### Solution that is respectful of bindings (I would suggest you go this route)
If you wanted to be respectful of bindings and automatically re-render the heatmap whenever the dataset is changed (probably the better way to do it), then you would want to instead create a different dataChanged method.

Instead of using addData (Which only adds points to the existing map) you would just use setData.

Then you could add a flag to the component like: `swappable` that when true disables the existing `dataChanged` method and, instead, enables the new `dataChanged` method.

so the result would be something like:
```
swappable: false,
dataChanged: Ember.observer('data.@each', function(){
   if (!this.get('swappable')){
      var data = this.get('data');
      if (this.get('hasRendered')){
        this.get('map').addData(data.objectAt(data.length - 1));
      }
  }
}),
dataChangedSwappable: Ember.observer('data.@each', function(){
   if (this.get('swappable')){
      var data = this.get('data');
      if (this.get('hasRendered')){
        this.get('map').setData(
            max: this.get('max'),
            min: this.get('min'),
            data: this.get('data')
        );
      }
  }
}),
```

**Comment by cloke** [comment]
I actually ended up going with your last suggestion. Is this something that you'd be willing to take a PR for? I want to changing my naming as I like swappable better, but otherwise this is almost exactly the solution I came up with.

**Comment by MLHale** [comment]
Sure you can make a PR.

**Comment by MLHale** [comment]
#3, closing
